package com.wintec.lamp.dao;

import com.wintec.lamp.dao.entity.AccDto;
import com.wintec.lamp.dao.entity.Commdity;
import com.wintec.lamp.dao.entity.PluDto;
import com.wintec.lamp.dao.entity.TagMiddle;
import com.wintec.lamp.dao.entity.TraceabilityCode;
import com.wintec.lamp.dao.entity.Transaction;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import java.util.Map;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig accDtoDaoConfig;
    private final DaoConfig commdityDaoConfig;
    private final DaoConfig pluDtoDaoConfig;
    private final DaoConfig tagMiddleDaoConfig;
    private final DaoConfig traceabilityCodeDaoConfig;
    private final DaoConfig transactionDaoConfig;

    private final AccDtoDao accDtoDao;
    private final CommdityDao commdityDao;
    private final PluDtoDao pluDtoDao;
    private final TagMiddleDao tagMiddleDao;
    private final TraceabilityCodeDao traceabilityCodeDao;
    private final TransactionDao transactionDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        accDtoDaoConfig = daoConfigMap.get(AccDtoDao.class).clone();
        accDtoDaoConfig.initIdentityScope(type);

        commdityDaoConfig = daoConfigMap.get(CommdityDao.class).clone();
        commdityDaoConfig.initIdentityScope(type);

        pluDtoDaoConfig = daoConfigMap.get(PluDtoDao.class).clone();
        pluDtoDaoConfig.initIdentityScope(type);

        tagMiddleDaoConfig = daoConfigMap.get(TagMiddleDao.class).clone();
        tagMiddleDaoConfig.initIdentityScope(type);

        traceabilityCodeDaoConfig = daoConfigMap.get(TraceabilityCodeDao.class).clone();
        traceabilityCodeDaoConfig.initIdentityScope(type);

        transactionDaoConfig = daoConfigMap.get(TransactionDao.class).clone();
        transactionDaoConfig.initIdentityScope(type);

        accDtoDao = new AccDtoDao(accDtoDaoConfig, this);
        commdityDao = new CommdityDao(commdityDaoConfig, this);
        pluDtoDao = new PluDtoDao(pluDtoDaoConfig, this);
        tagMiddleDao = new TagMiddleDao(tagMiddleDaoConfig, this);
        traceabilityCodeDao = new TraceabilityCodeDao(traceabilityCodeDaoConfig, this);
        transactionDao = new TransactionDao(transactionDaoConfig, this);

        registerDao(AccDto.class, accDtoDao);
        registerDao(Commdity.class, commdityDao);
        registerDao(PluDto.class, pluDtoDao);
        registerDao(TagMiddle.class, tagMiddleDao);
        registerDao(TraceabilityCode.class, traceabilityCodeDao);
        registerDao(Transaction.class, transactionDao);
    }
    
    public void clear() {
        accDtoDaoConfig.clearIdentityScope();
        commdityDaoConfig.clearIdentityScope();
        pluDtoDaoConfig.clearIdentityScope();
        tagMiddleDaoConfig.clearIdentityScope();
        traceabilityCodeDaoConfig.clearIdentityScope();
        transactionDaoConfig.clearIdentityScope();
    }

    public AccDtoDao getAccDtoDao() {
        return accDtoDao;
    }

    public CommdityDao getCommdityDao() {
        return commdityDao;
    }

    public PluDtoDao getPluDtoDao() {
        return pluDtoDao;
    }

    public TagMiddleDao getTagMiddleDao() {
        return tagMiddleDao;
    }

    public TraceabilityCodeDao getTraceabilityCodeDao() {
        return traceabilityCodeDao;
    }

    public TransactionDao getTransactionDao() {
        return transactionDao;
    }

}
