package com.wintec.lamp.bean;

import java.io.Serializable;

public class TagRules implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tag_rules.id
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tag_rules.bar_number
     *
     * @mbg.generated
     */
    private String barNumber;

    public String getPrefix() {
        return prefix;
    }

    public void setPrefix(String prefix) {
        this.prefix = prefix;
    }

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tag_rules.prefix
     *
     * @mbg.generated
     */
    private String prefix;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tag_rules.format
     *
     * @mbg.generated
     */
    private Integer format;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tag_rules.number_bits
     *
     * @mbg.generated
     */
    private Integer numberBits;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tag_rules.check_digit
     *
     * @mbg.generated
     */
    private Integer checkDigit;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tag_rules.print
     *
     * @mbg.generated
     */
    private Integer print;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tag_rules.branch_code
     *
     * @mbg.generated
     */
    private String branchCode;

    private int digits;

    //计件码前缀
    private String pieceWork;

    public String getPieceWork() {
        return pieceWork;
    }

    public void setPieceWork(String pieceWork) {
        this.pieceWork = pieceWork;
    }

    public int getDigits() {
        return digits;
    }

    public void setDigits(int digits) {
        this.digits = digits;
    }

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table tag_rules
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tag_rules.id
     *
     * @return the value of tag_rules.id
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tag_rules.id
     *
     * @param id the value for tag_rules.id
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tag_rules.bar_number
     *
     * @return the value of tag_rules.bar_number
     * @mbg.generated
     */
    public String getBarNumber() {
        return barNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tag_rules.bar_number
     *
     * @param barNumber the value for tag_rules.bar_number
     * @mbg.generated
     */
    public void setBarNumber(String barNumber) {
        this.barNumber = barNumber == null ? null : barNumber.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tag_rules.prefix
     *
     * @return the value of tag_rules.prefix
     *
     * @mbg.generated
     */

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tag_rules.format
     *
     * @return the value of tag_rules.format
     * @mbg.generated
     */
    public Integer getFormat() {
        return format;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tag_rules.format
     *
     * @param format the value for tag_rules.format
     * @mbg.generated
     */
    public void setFormat(Integer format) {
        this.format = format;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tag_rules.number_bits
     *
     * @return the value of tag_rules.number_bits
     * @mbg.generated
     */
    public Integer getNumberBits() {
        return numberBits;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tag_rules.number_bits
     *
     * @param numberBits the value for tag_rules.number_bits
     * @mbg.generated
     */
    public void setNumberBits(Integer numberBits) {
        this.numberBits = numberBits;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tag_rules.check_digit
     *
     * @return the value of tag_rules.check_digit
     * @mbg.generated
     */
    public Integer getCheckDigit() {
        return checkDigit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tag_rules.check_digit
     *
     * @param checkDigit the value for tag_rules.check_digit
     * @mbg.generated
     */
    public void setCheckDigit(Integer checkDigit) {
        this.checkDigit = checkDigit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tag_rules.print
     *
     * @return the value of tag_rules.print
     * @mbg.generated
     */
    public Integer getPrint() {
        return print;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tag_rules.print
     *
     * @param print the value for tag_rules.print
     * @mbg.generated
     */
    public void setPrint(Integer print) {
        this.print = print;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tag_rules.branch_code
     *
     * @return the value of tag_rules.branch_code
     * @mbg.generated
     */
    public String getBranchCode() {
        return branchCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tag_rules.branch_code
     *
     * @param branchCode the value for tag_rules.branch_code
     * @mbg.generated
     */
    public void setBranchCode(String branchCode) {
        this.branchCode = branchCode == null ? null : branchCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tag_rules
     *
     * @mbg.generated
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        TagRules other = (TagRules) that;
        return (this.getId() == null ? other.getId() == null : this.getId().equals(other.getId()))
                && (this.getBarNumber() == null ? other.getBarNumber() == null : this.getBarNumber().equals(other.getBarNumber()))
                && (this.getPrefix() == null ? other.getPrefix() == null : this.getPrefix().equals(other.getPrefix()))
                && (this.getFormat() == null ? other.getFormat() == null : this.getFormat().equals(other.getFormat()))
                && (this.getNumberBits() == null ? other.getNumberBits() == null : this.getNumberBits().equals(other.getNumberBits()))
                && (this.getCheckDigit() == null ? other.getCheckDigit() == null : this.getCheckDigit().equals(other.getCheckDigit()))
                && (this.getPrint() == null ? other.getPrint() == null : this.getPrint().equals(other.getPrint()))
                && (this.getBranchCode() == null ? other.getBranchCode() == null : this.getBranchCode().equals(other.getBranchCode()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tag_rules
     *
     * @mbg.generated
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getId() == null) ? 0 : getId().hashCode());
        result = prime * result + ((getBarNumber() == null) ? 0 : getBarNumber().hashCode());
        result = prime * result + ((getPrefix() == null) ? 0 : getPrefix().hashCode());
        result = prime * result + ((getFormat() == null) ? 0 : getFormat().hashCode());
        result = prime * result + ((getNumberBits() == null) ? 0 : getNumberBits().hashCode());
        result = prime * result + ((getCheckDigit() == null) ? 0 : getCheckDigit().hashCode());
        result = prime * result + ((getPrint() == null) ? 0 : getPrint().hashCode());
        result = prime * result + ((getBranchCode() == null) ? 0 : getBranchCode().hashCode());
        return result;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tag_rules
     *
     * @mbg.generated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", barNumber=").append(barNumber);
        sb.append(", prefix=").append(prefix);
        sb.append(", format=").append(format);
        sb.append(", numberBits=").append(numberBits);
        sb.append(", checkDigit=").append(checkDigit);
        sb.append(", print=").append(print);
        sb.append(", branchCode=").append(branchCode);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}